version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd ReinsuranceAIUI
      - echo "Installing dependencies..."
      - npm ci --production=false

  pre_build:
    commands:
      - echo "Running typecheck..."
      - npm run typecheck
      - echo "Running tests..."
      - npm run test
      - echo "Running formatting check..."
      - npx prettier --check .

  build:
    commands:
      - echo "Building the application..."
      - npm run build

  post_build:
    commands:
      - echo "Post-build: Listing files"
      - ls -la dist/

artifacts:
  files:
    - "**/*"
  base-directory: "ReinsuranceAIUI/dist"

cache:
  paths:
    - "ReinsuranceAIUI/node_modules/**/*"
    - "ReinsuranceAIUI/.npm/**/*"

env:
  variables:
    NODE_ENV: "production"
    CI: "true"
